### ISSUE TITLE
Not working here

### ISSUE THREAD

**Issue by krivbas1** [besuper/TwitchNoSub#75] opened 2023-05-06 15:48 UTC
https://www.twitch.tv/videos/1812835080

**Comment by Turkceqwertyx** [comment] 2023-05-19 08:49
it's working for me

**Comment by Turkceqwertyx** [comment] 2023-05-19 08:52
Which browser do you using? # @krivbas1

**Comment by BlueWorld1** [comment] 2023-05-20 15:15
Working on my side, not reproductable.

**Comment by onzostudio** [comment] 2023-06-06 12:57
Indeed, as Blovario said, the problem seems to be related to the recent update of Chromium/Brave. I fixed my problem by checking the extension, disabling it, and then reactivating it after a few seconds. The extension is now working properly. I also disabled Twitch protections, although I believe it is not necessary.

**Comment by Blovario** [comment] 2023-06-06 22:56
> Indeed, as Blovario said, the problem seems to be related to the recent update of Chromium/Brave. I fixed my problem by checking the extension, disabling it, and then reactivating it after a few seconds. The extension is now working properly. I also disabled Twitch protections, although I believe it is not necessary.

Yep, I did the same : disable, enable and just in case, reload the extension, it worked for me. No need to deactivate twitch protections in my case

**Comment by madmax2** [comment] 2023-06-07 09:49
@Blovario how do you deactivate twitch extensions?

**Comment by besuper** [comment] 2023-12-20 12:11
Hi, this should be fixed https://github.com/besuper/TwitchNoSub/commit/601a23b66c87853b5340e4dca91007cc8b3036a2

**Closed by besuper** 2023-12-20 12:11 UTC
Labels: bug
